services:
  db:
    image: bitnami/postgresql
    container_name: airbnb_auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/bitnami/postgresql
    networks:
      - microservices-network

volumes:
  auth_postgres_data:

networks:
  microservices-network:
    external: true
