services:
  db:
    image: bitnami/postgresql
    container_name: airbnb_property_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_db
    ports:
      - "5433:5432"
    volumes:
      - property_postgres_data:/bitnami/postgresql
    networks:
      - microservices-network

volumes:
  property_postgres_data:

networks:
  microservices-network:
    external: true
