services:
  db:
    image: bitnami/postgresql
    container_name: airbnb_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_db
    ports:
      - "5434:5432"
    volumes:
      - booking_postgres_data:/bitnami/postgresql
    networks:
      - microservices-network

volumes:
  booking_postgres_data:

networks:
  microservices-network:
    external: true
